name: run-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.1 ]
        laravel: [ 10.* ]
        stability: [ prefer-stable ]
        include:
          - laravel: 10.*
            testbench: 7.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_PASSWORD: secret
          MYSQL_USER: solawi_ut
          MYSQL_DATABASE: solawi_ut
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, xdebug
          coverage: xdebug

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install composer dependencies
        run: composer install --no-scripts

      - name: Prepare Laravel Application
        run: |
          php -r "file_exists('.env') || copy('.env.testing.example', '.env.testing');"
          php artisan key:generate --env=testing

      - name: Grant write permission to root
        run: chmod +w ./

      - name: Execute tests
        run: vendor/bin/pest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: build/logs/clover.xml
